version: '3'

services:
    dbproject:
        build: .\mytomcat
        ports:
        - 9090:8080
        depends_on:
        - db
    db:
        build: .\db
        ports:
        - 5432:5432
        volumes:
        - dbdata:/var/lib/postgresql/data
volumes:
    dbdata: